### ISSUE TITLE
Only a question

### ISSUE THREAD

**Issue by TOBIBLASTER00912** [Eralp232/KonasClient#1]
Is this client 1.19.3 too? I need it for a newer server and i dont know if this client do work in 1.19.3 
Thanks for reading :)

**Comment by Eralp232** [comment]
No, Konas Client supports 1.12.2 version only. But instead of you can use viaversion. With viaversion, you can connect to 1.19.3 servers from 1.12.2 client. Download viaversion for forge 1.12.2. Put viaversion jar to mods folder (put konas jar too) and run with forge 1.12.2. Have a good day.
